### ISSUE TITLE
Counts only max 1000 objects per bucket

### ISSUE THREAD

**Issue by molu8bits** [molu8bits/s3bucket_exporter#1]
Counts only max 1000 objects per bucket

**Comment by ramp23** [comment]
That function will fix it.
`func countBucketSize(bucketName string, s3Client *s3.S3) (float64, float64) {
	i := 0
	var bucketUsage float64
	var bucketObjects float64
	bucketUsage, bucketObjects = 0, 0

	err := s3Client.ListObjectsPages(&s3.ListObjectsInput{Bucket: aws.String(bucketName)}, 
		func(p *s3.ListObjectsOutput, last bool) (shouldContinue bool) {
			i++
			for _, obj := range p.Contents {
				bucketUsage += float64(*obj.Size)
				bucketObjects++
			}
			return true
		})

	if err != nil {
		log.Fatal(err)
		return 0, 0
	}
	return bucketUsage, bucketObjects
}`

**Comment by ramp23** [comment]
That function will fix it.




`func countBucketSize(bucketName string, s3Client *s3.S3) (float64, float64) {
	i := 0
	var bucketUsage float64
	var bucketObjects float64
	bucketUsage, bucketObjects = 0, 0

	err := s3Client.ListObjectsPages(&s3.ListObjectsInput{Bucket: aws.String(bucketName)}, 
		func(p *s3.ListObjectsOutput, last bool) (shouldContinue bool) {
			i++
			for _, obj := range p.Contents {
				bucketUsage += float64(*obj.Size)
				bucketObjects++
			}
			return true
		})

	if err != nil {
		log.Fatal(err)
		return 0, 0
	}
	return bucketUsage, bucketObjects
}`

**Comment by ramp23** [comment]
`func countBucketSize(bucketName string, s3Client *s3.S3) (float64, float64) {
	i := 0
	var bucketUsage float64
	var bucketObjects float64
	bucketUsage, bucketObjects = 0, 0

	err := s3Client.ListObjectsPages(&s3.ListObjectsInput{Bucket: aws.String(bucketName)}, 
		func(p *s3.ListObjectsOutput, last bool) (shouldContinue bool) {
			i++
			for _, obj := range p.Contents {
				bucketUsage += float64(*obj.Size)
				bucketObjects++
			}
			return true
		})

	if err != nil {
		log.Fatal(err)
		return 0, 0
	}
	return bucketUsage, bucketObjects
}`

**Comment by ramp23** [comment]
That code will fix it.

```
func countBucketSize(bucketName string, s3Client *s3.S3) (float64, float64) {
	i := 0
	var bucketUsage float64
	var bucketObjects float64
	bucketUsage, bucketObjects = 0, 0

	err := s3Client.ListObjectsPages(&s3.ListObjectsInput{Bucket: aws.String(bucketName)}, 
		func(p *s3.ListObjectsOutput, last bool) (shouldContinue bool) {
			i++
			for _, obj := range p.Contents {
				bucketUsage += float64(*obj.Size)
				bucketObjects++
			}
			return true
		})

	if err != nil {
		log.Fatal(err)
		return 0, 0
	}
	return bucketUsage, bucketObjects
}
```

**Comment by molu8bits** [comment]
fixed
