### ISSUE TITLE
How to set the endpoint url for aws s3?

### ISSUE THREAD

**Issue by stemid** [molu8bits/s3bucket_exporter#4]
If I knew how I would submit a PR for the README because this is really hard to figure out for someone who doesn't program and just wants to monitor s3 buckets.

I've tried all sorts of combinations I found in various docs like [this one](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html) and [this one](https://docs.aws.amazon.com/general/latest/gr/s3.html).

I get different errors depending on what url I try but here's on example using `S3_ENDPOINT=https://bucket-name.eu-central-1.s3.amazonaws.com:443`;

```
time="2021-05-11T21:34:15Z" level=info msg="Beginning to serve on port:9655"
time="2021-05-11T21:34:15Z" level=info msg="s3 name 'eu-central-1' available at s3 endpoint 'https://bucket-name.eu-central-1.s3.amazonaws.com:443' will be monitored"
time="2021-05-11T21:34:15Z" level=info msg="listenPort ::9655"
Connection to S3 endpoint failed : RequestError: send request failed
caused by: Get https://bucket-name.eu-central-1.s3.amazonaws.com:443/: x509: certificate is valid for *.s3.amazonaws.com, s3.amazonaws.com, not bucket-name.eu-central-1.s3.amazonaws.com
panic: inconsistent label cardinality: expected 1 label values but got 0 in []string(nil)

goroutine 10 [running]:
github.com/prometheus/client_golang/prometheus.MustNewConstMetric(...)
        /go/src/github.com/prometheus/client_golang/prometheus/value.go:107
main.S3Collector.Collect(0xc000088540)
        /build/main.go:84 +0xd3b
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /go/src/github.com/prometheus/client_golang/prometheus/registry.go:446 +0x19d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /go/src/github.com/prometheus/client_golang/prometheus/registry.go:457 +0x571
```

**Comment by pawanitzone** [comment]
I have the same issue. when we set s3 endpoint it gives an error just like what @stemid mentioned.

**Comment by molu8bits** [comment]
I have added examples how to run with AWS into README.
In general something like this work for me:

`./s3bucket-exporter -s3_endpoint https://s3.us-east-1.amazonaws.com -listen_port :9655 -s3_access_key ABCD12345678 -s3_secret_key mySecretKey -s3_name=My2S3Endpoint --s3_region=us-east-1 --s3_force_path_style=false --s3_disable_endpoint_host_prefix=true`


Anyway there is a problem with AWS S3 buckets. It will work only if there are buckets only in one region.
This exporter first gets a list of all the buckets and later iterate through each of them one by one. As long as all bucket found are from the same region its ok. When some bucket is found from other region than iteration would fail.

Some workaround currently is to create additional user and limit his view to see buckets only from one region. Then use credentials generated for this user.
