### ISSUE TITLE
Trying to do a docker-compuse up 

### ISSUE THREAD

**Issue by kimsvane** [molu8bits/s3bucket_exporter#5]
While i have filled the docker-compuose.yml with wasabi endpoint, etc. 
When i try to run it, i am given the following error: 

ysername@servername:~/s3bucket_exporter-master$ sudo docker-compose up
ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.s3bucketexporter.environment.S3_DISABLE_SSL contains false, which is an invalid type, it should be a string, number, or a null

**Comment by molu8bits** [comment]
Please try to use double quotation marks. docker-compose.yaml example in this repository has been updated.
